name: Compile JOSS Paper

on:
  push:
    branches:
      - joss_paper_submission
      
  pull_request:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Generate Paper PDF
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper_path: paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          # This should be the path to the paper within your repo.
          add: 'paper.pdf' # 'paper/*.pdf' to commit all PDFs in the paper directory